### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by pckennethma** [OSUSecLab/GAENPlus#1]
please see the screenshot and log file.
[log.txt](https://github.com/OSUSecLab/GAENPlus/files/9056486/log.txt)
![2022070700727427_972_1657124150191_0](https://user-images.githubusercontent.com/44944354/177597496-facc2175-2186-406e-93ab-d8a65e80774f.jpg)

**Comment by osu4321** [comment]
Thank you for the screenshot and log file. The latest commit should remedy this issue.
